FROM golang:1.20-buster AS build

WORKDIR /app

COPY . ./
RUN go mod download

RUN CGO_ENABLED=0 go build /apps/products/main.go -o /bin/app

## Deploy
FROM gcr.io/distroless/static-debian11

COPY --from=build /bin/app /bin
COPY .env.products.dev /bin

EXPOSE 1234

ENTRYPOINT [ "/bin/app", "/bin/.env.products.dev" ]