// Protobuf Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: modules/auth/authProto/auth.proto

package neversuitup_e_commerce_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAccessTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *FindAccessTokenReq) Reset() {
	*x = FindAccessTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authProto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccessTokenReq) ProtoMessage() {}

func (x *FindAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccessTokenReq.ProtoReflect.Descriptor instead.
func (*FindAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *FindAccessTokenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindAccessTokenReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type FindAccessTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FindAccessTokenRes) Reset() {
	*x = FindAccessTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authProto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccessTokenRes) ProtoMessage() {}

func (x *FindAccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccessTokenRes.ProtoReflect.Descriptor instead.
func (*FindAccessTokenRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *FindAccessTokenRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_modules_auth_authProto_auth_proto protoreflect.FileDescriptor

var file_modules_auth_authProto_auth_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x4d, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x52, 0x61, 0x79, 0x61, 0x74, 0x6f, 0x31, 0x35, 0x39, 0x2f, 0x6e, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x75, 0x69, 0x74, 0x75, 0x70, 0x2d, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x65, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_auth_authProto_auth_proto_rawDescOnce sync.Once
	file_modules_auth_authProto_auth_proto_rawDescData = file_modules_auth_authProto_auth_proto_rawDesc
)

func file_modules_auth_authProto_auth_proto_rawDescGZIP() []byte {
	file_modules_auth_authProto_auth_proto_rawDescOnce.Do(func() {
		file_modules_auth_authProto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_auth_authProto_auth_proto_rawDescData)
	})
	return file_modules_auth_authProto_auth_proto_rawDescData
}

var file_modules_auth_authProto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_auth_authProto_auth_proto_goTypes = []interface{}{
	(*FindAccessTokenReq)(nil), // 0: FindAccessTokenReq
	(*FindAccessTokenRes)(nil), // 1: FindAccessTokenRes
}
var file_modules_auth_authProto_auth_proto_depIdxs = []int32{
	0, // 0: AuthServices.FindAccessToken:input_type -> FindAccessTokenReq
	1, // 1: AuthServices.FindAccessToken:output_type -> FindAccessTokenRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authProto_auth_proto_init() }
func file_modules_auth_authProto_auth_proto_init() {
	if File_modules_auth_authProto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_auth_authProto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAccessTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_auth_authProto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAccessTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_auth_authProto_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authProto_auth_proto_goTypes,
		DependencyIndexes: file_modules_auth_authProto_auth_proto_depIdxs,
		MessageInfos:      file_modules_auth_authProto_auth_proto_msgTypes,
	}.Build()
	File_modules_auth_authProto_auth_proto = out.File
	file_modules_auth_authProto_auth_proto_rawDesc = nil
	file_modules_auth_authProto_auth_proto_goTypes = nil
	file_modules_auth_authProto_auth_proto_depIdxs = nil
}
