// Protobuf Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: modules/users/usersProto/users.proto

package neversuitup_e_commerce_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindOneUserByUsernameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *FindOneUserByUsernameReq) Reset() {
	*x = FindOneUserByUsernameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_users_usersProto_users_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneUserByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneUserByUsernameReq) ProtoMessage() {}

func (x *FindOneUserByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_users_usersProto_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneUserByUsernameReq.ProtoReflect.Descriptor instead.
func (*FindOneUserByUsernameReq) Descriptor() ([]byte, []int) {
	return file_modules_users_usersProto_users_proto_rawDescGZIP(), []int{0}
}

func (x *FindOneUserByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserForAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserForAll) Reset() {
	*x = UserForAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_users_usersProto_users_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserForAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserForAll) ProtoMessage() {}

func (x *UserForAll) ProtoReflect() protoreflect.Message {
	mi := &file_modules_users_usersProto_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserForAll.ProtoReflect.Descriptor instead.
func (*UserForAll) Descriptor() ([]byte, []int) {
	return file_modules_users_usersProto_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserForAll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserForAll) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserForAll) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type FindOneUserByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOneUserByIdReq) Reset() {
	*x = FindOneUserByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_users_usersProto_users_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneUserByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneUserByIdReq) ProtoMessage() {}

func (x *FindOneUserByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_users_usersProto_users_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneUserByIdReq.ProtoReflect.Descriptor instead.
func (*FindOneUserByIdReq) Descriptor() ([]byte, []int) {
	return file_modules_users_usersProto_users_proto_rawDescGZIP(), []int{2}
}

func (x *FindOneUserByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOneUserByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FindOneUserByIdRes) Reset() {
	*x = FindOneUserByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_users_usersProto_users_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneUserByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneUserByIdRes) ProtoMessage() {}

func (x *FindOneUserByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_users_usersProto_users_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneUserByIdRes.ProtoReflect.Descriptor instead.
func (*FindOneUserByIdRes) Descriptor() ([]byte, []int) {
	return file_modules_users_usersProto_users_proto_rawDescGZIP(), []int{3}
}

func (x *FindOneUserByIdRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_modules_users_usersProto_users_proto protoreflect.FileDescriptor

var file_modules_users_usersProto_users_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x54,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xce, 0x01, 0x0a, 0x0d, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x15, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x13, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x15,
	0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x41, 0x6c,
	0x6c, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x61, 0x79, 0x61, 0x74, 0x6f, 0x31, 0x35,
	0x39, 0x2f, 0x6e, 0x65, 0x76, 0x65, 0x72, 0x73, 0x75, 0x69, 0x74, 0x75, 0x70, 0x2d, 0x65, 0x2d,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_users_usersProto_users_proto_rawDescOnce sync.Once
	file_modules_users_usersProto_users_proto_rawDescData = file_modules_users_usersProto_users_proto_rawDesc
)

func file_modules_users_usersProto_users_proto_rawDescGZIP() []byte {
	file_modules_users_usersProto_users_proto_rawDescOnce.Do(func() {
		file_modules_users_usersProto_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_users_usersProto_users_proto_rawDescData)
	})
	return file_modules_users_usersProto_users_proto_rawDescData
}

var file_modules_users_usersProto_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_users_usersProto_users_proto_goTypes = []interface{}{
	(*FindOneUserByUsernameReq)(nil), // 0: FindOneUserByUsernameReq
	(*UserForAll)(nil),               // 1: UserForAll
	(*FindOneUserByIdReq)(nil),       // 2: FindOneUserByIdReq
	(*FindOneUserByIdRes)(nil),       // 3: FindOneUserByIdRes
}
var file_modules_users_usersProto_users_proto_depIdxs = []int32{
	0, // 0: UsersServices.FindOneUserByUsername:input_type -> FindOneUserByUsernameReq
	2, // 1: UsersServices.FindOneUserById:input_type -> FindOneUserByIdReq
	2, // 2: UsersServices.FindOneUserForAllById:input_type -> FindOneUserByIdReq
	1, // 3: UsersServices.FindOneUserByUsername:output_type -> UserForAll
	3, // 4: UsersServices.FindOneUserById:output_type -> FindOneUserByIdRes
	1, // 5: UsersServices.FindOneUserForAllById:output_type -> UserForAll
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_users_usersProto_users_proto_init() }
func file_modules_users_usersProto_users_proto_init() {
	if File_modules_users_usersProto_users_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_users_usersProto_users_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneUserByUsernameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_users_usersProto_users_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserForAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_users_usersProto_users_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneUserByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_users_usersProto_users_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneUserByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_users_usersProto_users_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_users_usersProto_users_proto_goTypes,
		DependencyIndexes: file_modules_users_usersProto_users_proto_depIdxs,
		MessageInfos:      file_modules_users_usersProto_users_proto_msgTypes,
	}.Build()
	File_modules_users_usersProto_users_proto = out.File
	file_modules_users_usersProto_users_proto_rawDesc = nil
	file_modules_users_usersProto_users_proto_goTypes = nil
	file_modules_users_usersProto_users_proto_depIdxs = nil
}
